use same pr flow

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -1,8 +1,6 @@
 name: Pull request
 
-on:
-  pull_request:
-    types: [ unlabeled ]
+on:  pull_request
 
 jobs:
   lint:
@@ -59,3 +57,35 @@ jobs:
         with:
           commit: ${{ github.event.workflow_run.head_sha }}
           files: "**/build/test-results/test/TEST-*.xml"
+
+  dependabot-test:
+    name: 🧪 Test for dependabot
+    #    (who triggered the workflow run) || (who is the pull-request author)
+    if: github.actor == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot[bot]'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v2
+        with:
+          java-version: 16
+          distribution: 'temurin'
+          cache: 'gradle'
+      - name: 🪲 Run test
+        run: ./gradlew test --fail-fast --no-daemon
+        timeout-minutes: 15
+
+  dependabot-version:
+    runs-on: ubuntu-latest
+    name: 🔰 ️Verify semantic version of dependencies
+    #    (who triggered the workflow run) || (who is the pull-request author)
+    if: github.actor == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot[bot]'
+    steps:
+      - name: 〽️ Fetch dependabot-metadata
+        uses: dependabot/fetch-metadata@v1.1.1
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+      - name: 🔗️ Merge minor/patch updates
+        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' }}
+        run: |
+          echo "Failing workflow because semver was ${{ steps.dependabot-metadata.outputs.update-type }}"
+          exit 1
